### ISSUE TITLE
Re-activating a deleted user

### ISSUE THREAD

**Issue by mschwemer** [xperseguers/t3ext-ig_ldap_sso_auth#104]
Hi,

we experience the following scenario:

If a user tries to authenticate in the frontend and the ldap connection is not available (== authentication fails) the user is set to deleted and a stop date is set. This is the wanted behaviour.

In the next "major" synchronisation (when the ldap connection is back again) the user will be undeleted / re-activated, but the stop date is still set. So the user is still not able to log in again. 

On the one hand, this is an edge case. On the other hand I would like to see this fixed. 

What do you think? 
Can you explain the reason for setting the stop date? 
Is it for documentation purposes, when the user tried to login?
Would it be OK to reset set stop date, when reactivating the user?

If you agree, I could provide a patch in the next weeks.

Thanks.

**Comment by xperseguers** [comment]
Hello, long time since you wrote, sorry! Did you happen to try to map "endtime" to 0? Just an idea...

**Comment by xperseguers** [comment]
Supposedly fixed with my suggestion more than 1 year ago.
