### ISSUE TITLE
Typo3 V10 LTS Support?

### ISSUE THREAD

**Issue by SchoolGuy** [xperseguers/t3ext-ig_ldap_sso_auth#106]
This was probably asked before but I wasn't able to find it: When will this extension support Typo3 10 LTS?

If there is anything I can do to make this happen please say so for me this extension is vital for my Typo3 Instance.

**Comment by xperseguers** [comment]
master branch is marked as compatible with TYPO3 v10 so please use that for the time being and open tickets with possibly PR if you find any problem. Once confirmed to work, an official release can naturally be created.
