### ISSUE TITLE
Additionnal fields in scheduler task

### ISSUE THREAD

**Issue by jlimassetEm** [xperseguers/t3ext-ig_ldap_sso_auth#109]
Hi,

First, thank you for your extension!

If we display a sheduler task detail, the choosen options of additionnal fiedls (mode, context, configuration, missinguserhandling and restoreduserhandling) are not selected (second screen shot). When I debug my task (first screen shot), I can see the right field's values.

Does any one can help?

Thanks

![task_debug](https://user-images.githubusercontent.com/68337099/91047920-235ca100-e61b-11ea-9451-902e797af6ac.PNG)
![task_displayed_options](https://user-images.githubusercontent.com/68337099/91047930-2788be80-e61b-11ea-8b3d-268b7635031f.PNG)

**Comment by mschwemer** [comment]
I can confirm the issue.

**Comment by xperseguers** [comment]
Indeed, broken since TYPO3 v9, I see that I fixed the "problem" in EXT:image_autoresize task, can inspire from it :)
