### ISSUE TITLE
Associated site configurations - option description not existent

### ISSUE THREAD

**Issue by hartundweich** [xperseguers/t3ext-ig_ldap_sso_auth#111]
Today we startet to experiment with LDAP integration. When creating the configuration the  part where associated site configurations are listed does not show anything in the right box. When I take a look at the source code I see the followiing:

`<option value="wienxtra_jahresbericht" title=""><div></div></option>`

So my site configuration is read but not displayed because title is missing - please tell me what can I do to display the title or make the title visible?

**Comment by xperseguers** [comment]
don't know how to reproduce.

**Comment by hartundweich** [comment]
![Screenshot_2020-09-22 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21](https://user-images.githubusercontent.com/18597291/93901149-8020a980-fcf6-11ea-8062-1bc9709452ac.png)
take a look at the screenshot - you can see where I have marked the untitled entry in the list

**Comment by hartundweich** [comment]
maybe it is because my site is in german language?

**Comment by xperseguers** [comment]
I tested on v10, but with your screenshot (and your comment), I now understand you are on v9. Still, I can't reproduce. Please share your domain configuration.

**Comment by hartundweich** [comment]
I still have two domain records - see the attached screenshot.
But also having site configuration - see the other screenshots for site configuration

![Screenshot_2020-09-23 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21](https://user-images.githubusercontent.com/18597291/93976890-ee5a8000-fd79-11ea-8530-b3c9b87ac475.png)

![Screenshot_2020-09-23 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21 (1)](https://user-images.githubusercontent.com/18597291/93977081-41343780-fd7a-11ea-8871-9e6805801850.png)
![Screenshot_2020-09-23 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21 (2)](https://user-images.githubusercontent.com/18597291/93977082-41ccce00-fd7a-11ea-966a-0f057f0cf189.png)
![Screenshot_2020-09-23 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21 (3)](https://user-images.githubusercontent.com/18597291/93977085-41ccce00-fd7a-11ea-9d8d-9c9257a96a8a.png)
![Screenshot_2020-09-23 wienXtra jahresbericht Development  TYPO3 CMS 9 5 21](https://user-images.githubusercontent.com/18597291/93977086-41ccce00-fd7a-11ea-8391-52c309ac7893.png)

**Comment by xperseguers** [comment]
OK, I guess I see somehow the problem... this is related to your "Einstiegspunkt", I made my tests by providing a full URL like `https://jahjresbericht.wienxtra.at/` instead of `/` otherwise TYPO3 is not able to generate full URL.

Any reason why you don't want to specify the domain anymore? Without that information, we will have to rely on the current host being used to access the Backend.

**Comment by xperseguers** [comment]
Please check this patch and report:

```
diff --git a/Classes/Tca/SiteConfigurationItemsProcFunc.php b/Classes/Tca/SiteConfigurationItemsProcFunc.php
index 89b8c32..5fe6a68 100644
--- a/Classes/Tca/SiteConfigurationItemsProcFunc.php
+++ b/Classes/Tca/SiteConfigurationItemsProcFunc.php
@@ -48,9 +48,13 @@ class SiteConfigurationItemsProcFunc
 
         $config['items'] = array_map(
             static function (Site $site) {
+                $host = $site->getBase()->getHost();
+                if (empty($host)) {
+                    $host = GeneralUtility::getIndpEnv('TYPO3_HOST_ONLY');
+                }
                 return [
                     // displayed value
-                    $site->getBase()->getHost(),
+                    $host,
                     // stored value
                     $site->getIdentifier()
                 ];
```

**Comment by hartundweich** [comment]
> 
> 
> OK, I guess I see somehow the problem... this is related to your "Einstiegspunkt", I made my tests by providing a full URL like `https://jahjresbericht.wienxtra.at/` instead of `/` otherwise TYPO3 is not able to generate full URL.
> 
> Any reason why you don't want to specify the domain anymore? Without that information, we will have to rely on the current host being used to access the Backend.


Specifying the host did the job - now everything is visible. 
I do not have the time ressources to check your patch at the moment. Maybe someone else can check the patch?

**Comment by xperseguers** [comment]
it's fixed in master branch, I'm sure the patch is fine :)
