### ISSUE TITLE
SSL connection to AD server

### ISSUE THREAD

**Issue by hartundweich** [xperseguers/t3ext-ig_ldap_sso_auth#112]
As I've managed the extension to start working and we can now authenticate against our AD, I thought it would be nice to have SSL activated. So I checked the according checkbox and switched the port to 636.
Sometimes it is working and everything is green in my status and sometimes I get the status "Can't contact LDAP server" - but I know that the host and port settings are correct becaus I'm using LDAPadmin to browse through our AD tree...

Same thing is happening when I try to use TLS - sometimes it works and then it stops working.

Where can I start to search?

**Comment by xperseguers** [comment]
I would suggest to Xdebug in step-by-step the connection and see what happens internally (PHP warning, possible error that is catched up, internal error message, ...)
