### ISSUE TITLE
Fail to Ban  or something to stop bruteforce attacks on Frontend logins

### ISSUE THREAD

**Issue by Schwuuuuup** [xperseguers/t3ext-ig_ldap_sso_auth#113]
Hi, 

as far as I know, there is no limit on login attempts on the frontend.

In our case, the userbase for frontend and backend are the same with a huge overlap betweend BE and FE Users, so both authenticate against the same LDAP.

I was asked what would happen, if anyone would bruteforce the login, and unfortunately, it seems there is nothing.
Is there a way to to so or could it be added to ig_ldap_sso_auth?

Best Regards
TOM

**Comment by xperseguers** [comment]
I feel like this is something outside of the scope of this extension as it makes sense regardless of the authentication (local, LDAP, ...) and as such it should better be implemented as another layer, maybe inspired by this old extension: https://extensions.typo3.org/extension/sysfire_failban/

**Comment by Schwuuuuup** [comment]
Maybe this is out of the scope of this extension but sysfire_failban ist really an old extension.. In my opinion it should be part of the core...

**Comment by xperseguers** [comment]
closing as won't fix (out-of-scope)
