### ISSUE TITLE
Wildcard Injection - Frontend and Backend Login

### ISSUE THREAD

**Issue by stephanederer** [xperseguers/t3ext-ig_ldap_sso_auth#117]
It's not possible to validate username.
LDAP-Login with asterisk, e.g. "myuser*ame" is possible, which enables wildcard injections.
LDAP injection is maybe also possible.

**Comment by xperseguers** [comment]
Please describe a bit more what you mean, thanks.

**Comment by stephanederer** [comment]
vgl. #126

**Comment by xperseguers** [comment]
Fixed with corresponding commit (but did not include a reference to this ticket so not closed automatically).
