### ISSUE TITLE
Can't make automatic login SSO works.

### ISSUE THREAD

**Issue by Treedent** [xperseguers/t3ext-ig_ldap_sso_auth#125]
Using TYPO3 V10.4.14 and ig_ldap_sso_auth V3.6.0 on MS Active Directory.

- Frontend and Backend users/group are synchronized correctly.
- BE and FE Connection with Active Directory work properly.
- Single Sign On (SSO) | enabled for frontend

When going to the login page, the autologin does not work. The ldap log tells:

[DEBUG] request="4aaa9cb9a4218" component="Causal.IgLdapSsoAuth.Service.AuthenticationService": No usergroups found.

Is someone has encountered this issue or where can I find more information about SSO configuration?

**Comment by xperseguers** [comment]
Hard to help without actual details, you should try to debug, I suspect that somehow the format of the username you get while using SSO is not compatible with what is expected by the ig_ldap_sso_auth extension.

Furthermore, the debug message you get with "No usergroups found" is a message coming from `\TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication::fetchGroupData`, not straight from the LDAP ext...
