### ISSUE TITLE
FE Authentication does not work with TYPO3 10.4.16

### ISSUE THREAD

**Issue by YolfTypo3** [xperseguers/t3ext-ig_ldap_sso_auth#127]
Hi Xavier,

Thanks again for this extension.

It seems that the lightweight TypoScriptFrontendController, line 694 in the Authentication class, now requires a Site object and a SiteLanguage object instead of 0 and '' when creating the instance of the TypoScriptFrontendController object.

A possible patch is to create an instance of  \TYPO3\CMS\Core\Site\Entity\NullSite for the site and an instance of \TYPO3\CMS\Core\Site\Entity\SiteLanguage for the language.

The call to $GLOBALS['TSFE']->initTemplate() is no more allowed.

Best regards

Laurent

**Comment by typo3rel** [comment]
Hi,
Same here in 10.4.19
 
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1561583122: TypoScriptFrontendController must be constructed with a valid Site object or a resolved site in the current request as fallback. None given.
```

Next Problem:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85666-TypoScriptFrontendController-initTemplate.html

I removed the complete $GLOBALS['TSFE'] parts and that works for me.
We only use the BE_USER authentication.

**Comment by netzlum** [comment]
Hi Laurent, did you get any error message? and did you solve the problem? I have the same behaviour but only get: "component="Causal.IgLdapSsoAuth.Service.AuthenticationService": Password not accepted:  - " in the logs.
I tried the bugfix from this pull request: https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/pull/121 but there is no change.
TYPO3 10.4.18 and ig_ldap_sso_auth 3.6.0.
And by the way: thank you Xavier (and all contributors) for this extension

**Comment by YolfTypo3** [comment]
Hi,
If it may help, I solved the problem with the folllowing code: 

```
            $GLOBALS['TSFE'] = GeneralUtility::makeInstance(
                \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::class,
                $GLOBALS['TYPO3_CONF_VARS'],
                new \TYPO3\CMS\Core\Site\Entity\NullSite(),
                new \TYPO3\CMS\Core\Site\Entity\SiteLanguage(
                    0,
                    '',
                    new \TYPO3\CMS\Core\Http\Uri('/'),
                    ['enabled' => true]
                    )
                );
//            $GLOBALS['TSFE']->initTemplate();
```

**Comment by netzlum** [comment]
Hi, thank you. But that didn't alter it. Did you get any error message in the error log? I do not. Only password "Password not accepted:  - "

**Comment by YolfTypo3** [comment]
Hi,
I do not have any error message. This patch solves the Core error. 
Best regards
Laurent

**Comment by xperseguers** [comment]
Please check branch `feature/TYPO3v11`, this must have been related to #121 and is now fixed. If so we may close this issue.

**Comment by xperseguers** [comment]
At least I can properly Frontend authenticate with TYPO3 v10

**Comment by YolfTypo3** [comment]
Hi Xavier,
The branch feature/TYPO3v11 works fine with TYPO3 v10.
Thank you for this great extension.
Best regards
Laurent
