### ISSUE TITLE
Support for Typo3 v11.5

### ISSUE THREAD

**Issue by ghollenstein** [xperseguers/t3ext-ig_ldap_sso_auth#129]
it would be greate to have a version which supports v11.5  --> User/Group sync is working, but during the Login an exception is thrown.

**Comment by webmaster-buw** [comment]
> it would be greate to have a version which supports v11.5 --> User/Group sync is working, but during the Login an exception is thrown.

@ghollenstein Could you post the exception here? Maybe it's the same:
_(1/2) Doctrine\DBAL\Exception\DriverException_
`An exception occurred while executing 'UPDATE `be_users` SET `uid` = ?, `pid` = ?, `tstamp` = ?, [...] WHERE `uid` = ?' with params [1, 0, "20211119144703Z", [...]`
where the tstamp argument has the datetime format 'yyyymmddhhmmssZ' insteadt of '1637329623'.
(In my case it happens with TYPO3 v10 / 10.3.31-MariaDB / PHP 7.4, but not with TYPO3 v10 / MySQL 5.5 / PHP 7.2)

**Comment by ghollenstein** [comment]
Thank your for your response - here is the requested exception: 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to Causal\IgLdapSsoAuth\Domain\Repository\Typo3GroupRepository::fetch() must be of the type string, null given, called in /var/www/html/qm/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/Authentication.php on line 581 | TypeError thrown in file /var/www/html/qm/typo3conf/ext/ig_ldap_sso_auth/Classes/Domain/Repository/Typo3GroupRepository.php in line 73. Requested URL: https://qms.martin.at/typo3/login?loginProvider=1433416747 

PHP Version 7.4.25

**Comment by webmaster-buw** [comment]
Similiar here:
```
(1/1) TypeError

Argument 3 passed to Causal\IgLdapSsoAuth\Domain\Repository\Typo3UserRepository::setUserGroups() must be of the type string, null given, called in /var/www/www.erp-thueringen.de/Extensions/ig_ldap_sso_auth/Classes/Library/Authentication.php on line 246
```
No group settings, just user authentication

**Comment by MarkusEhrlich** [comment]
Another error:
```
(1/1) TypeError
Argument 1 passed to Causal\IgLdapSsoAuth\Domain\Repository\Typo3GroupRepository::fetch() must be of the type string, null given, called in /var/www/html/backend/public/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/Authentication.php on line 586

in /var/www/html/backend/public/typo3conf/ext/ig_ldap_sso_auth/Classes/Domain/Repository/Typo3GroupRepository.php line 73
     * @param string $dn
     * @param string $groupName
     * @return null
     */
    public static function fetch(string $table, int $uid = 0, ?int $pid = null, ?string $dn = null, ?string $groupName = null): array
    {
        if (!GeneralUtility::inList('be_groups,fe_groups', $table)) {
            throw new InvalidUserGroupTableException('Invalid table "' . $table . '"', 1404891809);
        }
```

**Comment by MarkusEhrlich** [comment]
In my case, the following line returns a null value:
`$groupTable = static::$authenticationService->authInfo['db_groups']['table'];`

This causes my error see https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/issues/129#issuecomment-976547972.

When I debug `$authenticationService`, the array db_groups => table is missing.
This affects 2 places in `Classes/Library/Authentication.php`.
Where should db_groups => table come from?

**Comment by xperseguers** [comment]
FYI working a bit on v11 compatibility. Be sure naturally to checkout `feature/TYPO3v11`

**Comment by xperseguers** [comment]
Branch `feature/TYPO3v11` has reached a good stability, the extension largely works in TYPO3 v11 (not tested everything though) and Frontend authentication works. As such I'm closing this issue, will merge that branch onto the main development branch (`master`) and suggest to open dedicated tickets if you encounter further problems with either TYPO3 v11 or PHP 8.
