### ISSUE TITLE
compatible with CAS server?

### ISSUE THREAD

**Issue by xbouillet** [xperseguers/t3ext-ig_ldap_sso_auth#130]
Hello,

I am using ig_ldap 3.5.0 on a  TYPO3 9.5.31 version.
I would like to know if the extension can be used with a CAS server for SSO? We have a CAS system with a login box for another website. We would like to link this with TYPO3.
If it is possible to make ig ldap work with the CAS server, how to configure the URL of the login box  for the frontend in TYPO3?

Thanks :):)

**Comment by xperseguers** [comment]
Hello,

CAS has nothing to do with LDAP (unless you consider a possible "backend" for CAS in Active Directory for instance but nothing you "consume" from TYPO3.

It depends whether you're using a "CAS server" supporting multiple protocols (CAS, SAMLv1, SAMLv2, OAuth2, OpenID, ...) like Aperero or WSO2 and then you could possibly use another extension of mine https://extensions.typo3.org/extension/oidc 

HTH but nothing related to this extension :)

**Comment by xbouillet** [comment]
Thank you very much for the explanations.
I understand much better.
Maybe I'll use your extension.
Thanks for the work done on the auth :)
Have a good day
