### ISSUE TITLE
User LDAP and User TYPO3

### ISSUE THREAD

**Issue by xbouillet** [xperseguers/t3ext-ig_ldap_sso_auth#131]
Hello,

I am using ig_ldap in v3.5.
I would like to have both users manually defined (thus authenticated with a TYPO3 password) and users authenticated with LDAP.

My login box works for LDAP users but not for others.

I can see in the FAQ, the following answer:
_For frontend and backend authentication, it is possible to manually define users not linked to your LDAP server (s). When a user is manually defined, the column of the tx_igldapssoauth_dn record is empty and therefore, since LDAP authentication will fail, it will automatically revert to the standard TYPO3 authentication service. This behavior can be enabled / disabled globally for the backend and / or the frontend in Extension Manager._

But, I don't see this option in the manager extension.

Any helps?

Thanks

**Comment by xperseguers** [comment]
E.g. for Backend users:
![image](https://user-images.githubusercontent.com/646805/171861614-e44e759c-c1b5-47ac-8def-541f8549bb92.png)
