### ISSUE TITLE
ImportUser only one transaction for all imports

### ISSUE THREAD

**Issue by someplace53** [xperseguers/t3ext-ig_ldap_sso_auth#135]
I have the question why the ImportUsers scheduled task does all the imports in one transaction? In my opinion it would be more convenient if every import would be its own transaction (than you should be able to remove the transaction statement).
1. The transaction is blocking the table for quiet some time (especially if you have a lot of groups), which can block logins
2. It is a bit annoying if one of the groups fails non of the groups will be synchronized
3. if an import fails, the log is only written to the log file, which at least I only check seldomly
4. why check all groups if already one failed?

It should not be hard to remove the transaction and I would be willing to do that, but maybe there are reason why I should not?
The problem with the log I do not know how to fix and so I would not.

**Comment by someplace53** [comment]
This would be an improvement :-) and would work for me. I assume you are aware of the missing `commit()` and the `continue` statement, which might make this a bit more complicate.

**Comment by xperseguers** [comment]
The import is about to be migrated to a Symfony command where the import only takes care of a single configuration record at once, thus fixing this issue at the same time :)

Will be part of official release later today.
