### ISSUE TITLE
Handling of missing users deletes all accounts

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#136]
In the scheduler task when I set Handling of missing users to delete every user gets deleted (deleted = 1). But the users exist.

I am currently on TYPO3 9.5.31.
LDAP is eDirectory (Microfocus).

**Comment by klodeckl** [comment]
In BE context, for FE users it works as expected

**Comment by xperseguers** [comment]
Trying to reproduce:

- Create a scheduler task of class "Import LDAP users"
- Set Mode to "Import missing LDAP users and synchronize existing TYPO3 users"
- Set Context to "Backend"
- Set Configuration to "All"
- Set Handling of missing users to "Delete"
- Set Handling of restored users to "Do nothing"

Run the task

**Expected**

- Already imported LDAP users which do not exist anymore in LDAP gets deleted
- Other users are updated/kept enabled

**Actual**

- Missing users get imported
- Existing LDAP accounts get deleted

=> can reproduce.
