### ISSUE TITLE
Data too long for column 'title' at row 1 while importing users and groups

### ISSUE THREAD

**Issue by FloMeyer** [xperseguers/t3ext-ig_ldap_sso_auth#142]
Hi,
i recently upgraded from 3.6.0 to 3.7.0 and now i get an error while trying to import users:
An exception occurred while executing 'UPDATE `be_groups` SET `uid` = ?, `pid` = ?, `tstamp` = ?, `title` = ?, `non_exclude_fields` = ?, `explicit_allowdeny` = ?, `allowed_languages` = ?, `custom_options` = ?, `db_mountpoints` = ?, `pagetypes_select` = ?, `tables_select` = ?, `tables_modify` = ?, `crdate` = ?, `cruser_id` = ?, `groupMods` = ?, `file_mountpoints` = ?, `file_permissions` = ?, `hidden` = ?, `description` = ?, `lockToDomain` = ?, `deleted` = ?, `TSconfig` = ?, `subgroup` = ?, `zzz_deleted_hide_in_lists` = ?, `workspace_perms` = ?, `category_perms` = ?, `tx_cal_enable_accesscontroll` = ?, `tx_cal_calendar` = ?, `tx_cal_category` = ?, `zzz_deleted_eu_ldap` = ?, `tx_igldapssoauth_dn` = ?, `tx_oelib_is_dummy_record` = ?, `tx_seminars_events_folder` = ?, `tx_seminars_registrations_folder` = ?, `tx_seminars_auxiliaries_folder` = ? WHERE `uid` = ?' with params [92, 0, 1624300293, "long_group_name_here_52_characters_long", null, null, "", null, "1880", "", null, null, 1624300270, 136, null, "46", "readFolder,writeFolder,addFolder,renameFolder,moveFolder,deleteFolder,readFile,writeFile,addFile,renameFile,replaceFile,moveFile,copyFile,deleteFile", 0, null, "", 0, null, "3", 0, 1, null, 0, "", "", 0, "CN=blablabla,DC=bla,DC=local", 0, 0, 0, 0, 92]: **Data too long for column 'title' at row 1**

My AD Group Name has 52 characters and now seems to be too long for backend groups. 

I am on Typo3 9.5.. it's old, i know, sorry. :)

Did you change the max length of the database field? Could you please increase it to e. g. 64 characters?

Best Regards,
Florian

**Comment by xperseguers** [comment]
Hello,

If you have a look at https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/ext_tables.sql you'll see that this extension does not enforce any limitation on that `title` field. So I can't do anything.

However you may extend it on your own by adding a `ext_tables.sql` file to your site extension and adapt that field's table accordingly. Then TYPO3's install tool will take your extended definition into account.

**Comment by FloMeyer** [comment]
Ahh thank you. It is even more different than i thought.

'title' is a field in 'be_groups'.. so this is not a field from an extension, i think.

 describe be_groups;
+----------------------------------+----------------------+------+-----+---------+----------------+
| Field                            | Type                 | Null | Key | Default | Extra          |
+----------------------------------+----------------------+------+-----+---------+----------------+
| uid                              | int(11) unsigned     | NO   | PRI | NULL    | auto_increment |
| pid                              | int(11) unsigned     | NO   | MUL | 0       |                |
| tstamp                           | int(11) unsigned     | NO   |     | 0       |                |
| title                            | varchar(50)          | NO   | MUL |         |                |
....

title is limited to 50 characters. I just wonder why it was functional before upgrading the extension.

So.. thank you for your fast reply!
