### ISSUE TITLE
Maintenance / Rebuild PHP Autoload Information disabled after install 

### ISSUE THREAD

**Issue by mtecfred** [xperseguers/t3ext-ig_ldap_sso_auth#152]
Typo3 11.5.10 on Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-125-generic x86_64) with PHP version:  7.4.30

After 
_composer req causal/ig_ldap_sso_auth_      
 and       
 _./vendor/bin/typo3 extension:setup_

the Maintenance / Rebuild PHP Autoload Information is disabled after install: 

![grafik](https://user-images.githubusercontent.com/20945133/188394277-ef4bd358-4b59-4821-8a26-b7ed51ada869.png)

Also dumping of the class loading information manually via cli by invoking autoload_classmap.php and autoload_psr4.php etc. won't help.

How to get it enabled again?

**Comment by xperseguers** [comment]
Please read the comment at the end of the "Rebuild PHP Autoload information" block, that has nothing to do with that extension. You may use

```bash
composer dumpautoload
```
