### ISSUE TITLE
PHP Warning: Undefined array key "uid" in backend regarding IconFactory.php when using PHP 8

### ISSUE THREAD

**Issue by axelp94** [xperseguers/t3ext-ig_ldap_sso_auth#162]
Hi,

In the TYPO3 backend list module I get the following message when i will add a new record.

PHP Warning: Undefined array key "uid" in /srv/www/htdocs/dev/t5dusdev.itk.local/web/typo3conf/ext/ig_ldap_sso_auth/Classes/Hooks/IconFactory.php line 46

Line of code:
**46:  $row = \TYPO3\CMS\Backend\Utility\BackendUtility::getRecord($table, $row['uid']);**

Regards,
Axel Peltzer

**Comment by xperseguers** [comment]
Please debug that line in your install. I tried with TYPO3 v11 and `$row['uid']` is always properly defined in my case. I suspect you may have some extension/record in that folder that behaves oddily.

Please try to figure out "when" `$row` is missing the `uid` key (or when it's null or whatever).

Thanks.

**Comment by siwa-pparzer** [comment]
error occurs when you create a new record in an empty folder for example
the items in the list of possible tables don't have an uid

**Comment by xperseguers** [comment]
Sorry but I tried to create arbitrary records (sys_category, tt_content, ...) in an empty folder, in TYPO3 v11 with PHP 8.1 and I just don't see the bug.

**Comment by xperseguers** [comment]
I'd say #165 should solve this issue, could you please test on your side?

Sidenote: I was naturally testing in Debug mode, and not in Production.

**Comment by siwa-pparzer** [comment]
yes, #165 solves the issue

**Comment by xperseguers** [comment]
thanks. thus closed while merging #165
