### ISSUE TITLE
Deprecation in TYPO3v11 with PHP 8.1: parameters of selectFromMembership function

### ISSUE THREAD

**Issue by cstrizzolo** [xperseguers/t3ext-ig_ldap_sso_auth#166]
I'm running ig_ldap_sso_auth 3.7.1 on TYPO3v11 and PHP 8.1 
The following deprecation notice gets added to the deprecation log:

Wed, 15 Feb 2023 08:27:07 +0100 [NOTICE] request="7a6c1bb9d9442" component="TYPO3.CMS.deprecations": Core: Error handler (BE): PHP Runtime Deprecation Notice: Optional parameter $membership declared before required parameter $filter is implicitly treated as a required parameter in (...)/typo3conf/ext/ig_ldap_sso_auth/Classes/Library/LdapGroup.php line 41 

Maybe the order of the selectFromMembership function parameters inside LdapGroup.php could be re-organized so as to avoid the above notice, by moving the optional parameter $membership after all the required parameters.

**Comment by xperseguers** [comment]
Fixed with #173
