### ISSUE TITLE
Wish: Screenshot of Extension-Configuration in manual or a section 'how to install'

### ISSUE THREAD

**Issue by Padina14** [xperseguers/t3ext-ig_ldap_sso_auth#168]
In TYPO3 it is common that you configure your extension with Typoscript. 
It is unusual that you use the extension settings for this.

I've been wondering why the extension isn't running and wasted a lot of time troubleshooting because I couldn't find any reference to the extension settings on a cursory look through the documentation. 
A screenshot or a 'how to install' chapter would have helped me.

**Comment by xperseguers** [comment]
No, in TYPO3 there are many extensions that are configured another way, moreover when there's either nothing related to the Frontend, or in this case, when there's Backend configuration as well, as TS is only for Frontend!

There's a wizard to help you create your configuration record.

If you read the documentation, and go straight to the administrator manual, which is what you are in case you install it in your TYPO3 website, you'll see everything you need to do: https://docs.typo3.org/p/causal/ig_ldap_sso_auth/3.7/en-us/AdministratorManual/Index.html

Too bad you missed it but now you know :)

**Comment by Padina14** [comment]
I think, you missunderstood me. I meant the following part of the configuration for your pretty good extension.
![Bildschirmfoto 2023-03-03 um 16 37 07](https://user-images.githubusercontent.com/63228213/222762430-ec11231c-5dc1-45db-93b3-44a463e6f68f.png)
