### ISSUE TITLE
[WISH] Upgrade for TYPO3v12 compatibility

### ISSUE THREAD

**Issue by ByteBandito** [xperseguers/t3ext-ig_ldap_sso_auth#169]
Just wishing this extension for TYPO3v12.

Thanks for the great extension!
Patrick

**Comment by CIMEOS** [comment]
Hi ! Any news about v12 compatibility ?

**Comment by ByteBandito** [comment]
No, It is still not updated :-(.

**Comment by ByteBandito** [comment]
(mistake - did not want to close the issue)

**Comment by xperseguers** [comment]
Hi, this extension will ultimately get compatibility for v12, naturally, but not having any project "near v11" right now and much to do in the next few months, I don't plan to work on it for fun.

Best to help here would first to try it under v12 and see what actually breaks...

**Comment by ByteBandito** [comment]
It breaks completly :-). When installed, the backend is just empty. Nothing. Frontend the same.

I need to remove it by editing the PackageStates.php manually and removing it.

No entry in error-log.

**Comment by ByteBandito** [comment]
Hi... any news on this?? :'-(

**Comment by agendartobias** [comment]
Hey does anyone have this extension ready for 12? We can sponsor it

**Comment by a-r-m-i-n** [comment]
Hi,
I'm also looking for a TYPO3 12 version of ig_ldap_sso_auth.

> the PR won't be merged as-is as it unfortunately doesn't respect the spirit of the extension being compatible for 2 LTS and I have no spare time to work on it right now.

Maybe it is time to break up with this requirement? TYPO3 v12 brought so many changes, especially in the Backend (JS modules, Ckeditor, ModuleRegistration, etc.) that I've also decided for my own extensions to drop the support of several LTS versions, because of too much efforts.

Better to have a TYPO3 12 only version, rather than no working version, I guess?

**Comment by afle** [comment]
Deprecated method are used, which a removed in v12.
e.g. "TYPO3\CMS\Extbase\Domain\Model\BackendUserGroup"

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94654-GenericExtbaseDomainClasses.html

**Comment by baschny** [comment]
Just as an idea:

You could support v12 and forward-support v13 already (by not using deprecated functions in v12), keeping the "2 releases spirit" but avoiding the hassle of keeping if/else switches to cope with the amount of changes brought by the v12 release.

Having a legacy v11/v10 branch for patches and fixes for the old release is still possible.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
+1

> Better to have a TYPO3 12 only version, rather than no working version, I guess?

Yes, much better! This is the only extension that prevents us from updating to 12 and we cannot drop it. :-/

**Comment by LightsOnDeveloper** [comment]
From what I read here, nobody knows if and when this extension will be available for typo3 12? A statement from the developers about when you can expect the extension for v12 or whether it needs support - be it financial or through man power - would be really great and would make planning for upcoming updates to 12 easier.

**Comment by julianhofmann** [comment]
As already written by @mschwemer:

> There is a fork at https://github.com/DMKEBUSINESSGMBH/t3ext-ig_ldap_sso_auth/
> 
> We use this already in several production environments.

https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/pull/174#issuecomment-1954183741

**Comment by xperseguers** [comment]
Please use `master` branch before official release.
