### ISSUE TITLE
Throw exception if group is not added

### ISSUE THREAD

**Issue by pixelbrackets** [xperseguers/t3ext-ig_ldap_sso_auth#17]
Feature request: Throw exception if adding a group is not possible in backend module.

**Situation**

The backend module lists groups and it is possible to import them into the CMS using a button.

Expected behavoir: Add new groups to the CMS.

Actual behaviour (on my instance): Start the import process upon button click, but then fail silently (no error message apears in the AJAX request) .

**Reason**

In my case the installation uses PostgreSQL, which failed when I tried to add a new group, because the given dataset did not match with the expected SQL query statement.

The insert statement then fails, but the module doesn't show an error.

Line 451 should throw an exception if adding the group was not possible for whatever reason:
 https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Controller/ModuleController.php#L451

(The same behavour applies to »Authentication«.)

**Comment by xperseguers** [comment]
Is it related to #30?
