### ISSUE TITLE
Bug: Pressing "+"-Button in List Modul on PID 0 throws Exception in IconFactory

### ISSUE THREAD

**Issue by josefglatz** [xperseguers/t3ext-ig_ldap_sso_auth#170]
## How to reproduce in TYPO3 11.5.latest

1. Open list module
2. Press on New Record button in the docmodulebutton area

<img width="226" alt="image" src="https://user-images.githubusercontent.com/2861556/227116563-f37591fb-1f39-4be6-95a6-e6174fedd3f2.png">

Now you get the Exception  **#1476107295 TYPO3\CMS\Core\Error\Exception**:

> PHP Warning: Undefined array key "uid" in /var/www/html/vendor/causal/ig_ldap_sso_auth/Classes/Hooks/IconFactory.php line 46

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/2861556/227116713-da0bca4d-119d-4348-9f2c-00e9fe114a8f.png">

**Comment by dasoe** [comment]
Same here. TYPO3 11.5., php 8 only.
Thanks for looking in!

**Comment by xperseguers** [comment]
This has been fixed since 24.01.2023 as part of eca798574
