### ISSUE TITLE
Login in TYPO3 11 with PHP 8.2 did not work since $GLOBALS['TYPO3_REQUEST'] was empty.

### ISSUE THREAD

**Issue by moritzkiehl** [xperseguers/t3ext-ig_ldap_sso_auth#179]
Hey, I encountered an error when trying to log into one of the Systems I tried to upgrade to PHP 8.2 and I could narrow it down to the fact that $GLOBALS['TYPO3_REQUEST'] was empty. Maybe there is another error which causes this.

Anyway I added another fallback to check if we are in a FE or BE Context on my [fork](https://github.com/moritzkiehl/t3ext-ig_ldap_sso_auth/commit/a7b8274f43eb3bdd3b047d23f0178bde4c5b3fee) but the rector upgrades for more PHP 8.2. Compatibility break some things if used with PHP 7.4, so I did not open a PR.

There is probably a better/smarter solution or even a fix to the fact that $GLOBALS['TYPO3_REQUEST'] was empty in my Installation.

**Comment by xperseguers** [comment]
Fixed with #183. Thanks for reporting.
