### ISSUE TITLE
301c659 breaks 11LTS-compatibility due to wrong group table lookup

### ISSUE THREAD

**Issue by jpmschuler** [xperseguers/t3ext-ig_ldap_sso_auth#183]
With dev-master I had the problem that although group sync was disabled and keep be groups was enabled, my users be_groups were manipulated (not all groups retained, only some).
Found out that the SQL query for checking the groups referred to the wrong table:
https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/785ade1b309d91e0a159ecea827c959e721fc69e/Classes/Domain/Repository/Typo3UserRepository.php#L376 creates an SQL query referring to the wrong table.
Called by https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/785ade1b309d91e0a159ecea827c959e721fc69e/Classes/Library/Authentication.php#L257 

However the table here was fe_groups, thus the chaos. So somehow the new implementation of
https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/785ade1b309d91e0a159ecea827c959e721fc69e/Classes/Library/Authentication.php#L917-L928
is not correct for 11LTS

333c92f is the version before that, which works fine in that regard - and not deep enough in 12LTS to provide a fix, but thought to at least mention the bug

**Comment by chrosey** [comment]
having the same issue with TYPO3 11.5
in my case Library/Authentication.php has neither `static::$authenticationService` or `$GLOBALS['TYPO3_REQUEST']` available. Then it assumes `fe_groups` is the right table.
