### ISSUE TITLE
Ldap server certificate chain will change. Is this a problem?

### ISSUE THREAD

**Issue by zottelmann** [xperseguers/t3ext-ig_ldap_sso_auth#186]
Hello!

Our IT-Department will be changing the Certificate-Chain of our ldap server. Can this cause a Problem with the extension? Version is 3.6

Thanks!

**Comment by xperseguers** [comment]
it shouldn't as long as your new certificate/chain is properly recognized by PHP.

**Comment by zottelmann** [comment]
Thank you!
