### ISSUE TITLE
Will the extension be updated to EntraID and TYPO3 V12?

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [xperseguers/t3ext-ig_ldap_sso_auth#191]
Hi all, 

we would like to use the extension in a v12 project that needs to be connected to MS Azure / EntraID. 

Is development in this direction already in the planning?

thx and best
Ben

**Comment by xperseguers** [comment]
For TYPO3 v12, this is ongoing, please switch to branch `feature/TYPO3v12`. For Microsoft EntraID, unsure if this will compatible, it looks like this doesn't support LDAP protocol but is something like OAuth2 and/or OpenID Connect. You may want to try another extension instead: https://extensions.typo3.org/extension/oidc (check dev repository for TYPO3 v12).

There are many other similar tickets, closing it.

**Comment by vb-benjamin-eyring** [comment]
Thanks for the hint!
