### ISSUE TITLE
dev-master not working with php 8.2

### ISSUE THREAD

**Issue by hartundweich** [xperseguers/t3ext-ig_ldap_sso_auth#198]
We are using Typo3 V11.5.34 with ig_ldap_sso - when upgrading PHP to 8.2 we switched ig_ldap_sso from 3.7.1 to dev-master.
At this point LDAP Login is not possible any more. Scheduler task is failing on command line - no helpful output from the debug log.
But when we try to create a new scheduler task for ig_ldap_sso we get an typo3 503 error when we want to save the task:

`Causal\OgLdapSsoAuth\Task\ImportUsers:setConfiguration(): Return value must be of type Causal\IgLdapSsoAuth\Task\ImportUsers, none returned.`

When changing back to ig_ldap_sso V3.7.1 everything is working smooth with PHP 8.2 although ig_ldap_sso is not supposed to work with PHP 8.2

It would be nice if this can be fixed - or give us some hint if our PHP 8.2 settings have to be adjusted. We are using the same settings as of PHP 8.1

Best,
Andreas

**Comment by someplace53** [comment]
This is probably a bug, there is a missing return statement in this [method](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/668144a89bf0750a57d1b7e09005189935367570/Classes/Task/ImportUsers.php#L305)
