### ISSUE TITLE
v 3.8.0 stopped working

### ISSUE THREAD

**Issue by frobert** [xperseguers/t3ext-ig_ldap_sso_auth#199]
Hi, not sure the reason but version 3.8.0 is not working anymore on TYPO3 v 11, it is not connecting to AD/LDAP via VPN as the version 3.7.1 ... After downgrade to v 3.7.1 it works as expected.

best regards

**Comment by josefglatz** [comment]
We have exactly the same situation on the servers (Gentoo OS) of our customer **BUT can not** reproduce the problems within DDEV (running Apache, same major PHP-version, connected via SSH tunnel to AD/LDAP)

- TYPO3 11 LTS
- PHP 8.2
- extension version 3.7.1 works o-o-t-b on the productive system

**Comment by josefglatz** [comment]
**Looks like #198 is somehow related**
