### ISSUE TITLE
LDAP Import user -> filter not working

### ISSUE THREAD

**Issue by airbenich** [xperseguers/t3ext-ig_ldap_sso_auth#2]
TYPO3 Version: 8.7.9
Extension Version: 3.2.2

Hey there,

i have a problem while making an scheduled LDAP import with this extension. In the configuration of my LDAP i set the "Filter" to: `(&(objectClass=person)(sAMAccountName={USERNAME}))`

But when executing the import via the TYPO3 Scheduler this filter is ignored and all users will be imported. When i execute this filter on the in the extensions "Search Wizard" it works perfectly.

Is there something i forgot to configure or is this a bug?

Thank you and greetings,
Vivian

**Comment by airbenich** [comment]
Someone out there? :)

**Comment by xperseguers** [comment]
Yes there is someone :) This is not clear. Your filter is doing virtually nothing, it shows LDAP objects of class `person` with "any" `sAMAccountName`. So effectively this shows *any* user.

When importing, the task is effectively replacing following markers with an asterisk:

- `{USERNAME}`
- `{USERDN}`
- `{USERUID}`

What do you mean by "this filter is ignored"? Which user you import is not matching this filter? Sounds odd, as explained.

**Comment by airbenich** [comment]
Great :) 

all our LDAP-Users are imported without any filtering. But in the configuration of this Extension i made the following settings:

![screenshot-2018-2-26 sdh intranet typo3 cms 8 7 9](https://user-images.githubusercontent.com/13045725/36661496-ac8e2d12-1adb-11e8-8a74-c6380ab9a044.png)

**Comment by xperseguers** [comment]
Please debug this line to understand why the filter does not seem to be taken into account: https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Utility/UserImportUtility.php#L143

**Comment by airbenich** [comment]
Ok thank you! It looks like the error is in the group assingment at our Active Directory-Server. Sorry for the inconvenience! & thank you for your help!
