### ISSUE TITLE
Exception if creating scheduler task

### ISSUE THREAD

**Issue by spoonerWeb** [xperseguers/t3ext-ig_ldap_sso_auth#200]
Version: 3.8.0
TYPO3: v11

If creating a scheduler task to import users there is an exception on save:

<img width="1140" alt="grafik" src="https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/assets/1793083/c9cf7cc7-c04b-45f8-a6cd-23d60606c811">

**Solution**:
Add a `return $this;` to the `setConfiguration()` method.

**Comment by klodeckl** [comment]
Same here when updating an existing scheduler task.
