### ISSUE TITLE
Exception after Update php7.4 to php8.2

### ISSUE THREAD

**Issue by Padina14** [xperseguers/t3ext-ig_ldap_sso_auth#203]
After the update from php7.4 to php8.2 I got a exception (see screenshot)
I used the dev-master-branch.

The reason.
The operator @ won't hide  fatal errors in php8+. (https://www.php.net/manual/en/migration80.incompatible.php)  

I develop the attached patch.
[ig_ldap_sso_auth-LdapUtility.patch](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/files/14759209/ig_ldap_sso_auth-LdapUtility.patch)
![Bildschirmfoto 2024-03-26 um 14 36 13](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/assets/63228213/2fe2f691-2a39-4497-89f5-a1142ef89e15)

**Comment by xperseguers** [comment]
Thanks for reporting. Problem is fixed in branch `feature/TYPO3v12`. Further work will be done those days before merging to master and hopefully releasing.
