### ISSUE TITLE
Typo3 v12 compatibility

### ISSUE THREAD

**Issue by thomasmuench** [xperseguers/t3ext-ig_ldap_sso_auth#206]
Hello,

Typo3 v11 ends soon and 12 is stable since lagem. Will there be an official version with Typo3 v12 support by October 24? 

Unfortunately the codes provided here so far do not work satisfactorily.

Thank you

**Comment by YetiCGN** [comment]
This would be interesting for us as well. I've seen the branch `feature/TYPO3v12`, but what's the plan on this as time is about to run out?

**Comment by xperseguers** [comment]
Content from `feature/TYPO3v12` has been merged onto `master`. Plan is to release officially soon. Stay tuned.

In the mean time, current `master` is supposed to be "as compatible" as any other TYPO3 v12 fork you can/could find out there so please do not hesitate to test and report problems, ideally before official release :)

**Comment by YetiCGN** [comment]
Okay, the time before an official release was a bit short but we have updated now and will give feedback should any issue arise.

Thanks a lot!
