### ISSUE TITLE
Wrong Server Configuration for Active Directory

### ISSUE THREAD

**Issue by jonnsn** [xperseguers/t3ext-ig_ldap_sso_auth#207]
since [6a4c5367f601a95db73567de5d9962cfad69c7d5](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/commit/6a4c5367f601a95db73567de5d9962cfad69c7d5) login and search does not work with Active Directory anymore.
The value of $config['server'] is '1' in my case (Version 3.8.0 with TYPO3 11, PHP 8.2).
The search still works if the option "First entry only" is checked.
Without this option no results are found.

When undoing the mentioned commit it will work again.
I am unsure of unwanted sideeffects though as I suggest the commit was done for a reason and was tested somehow.

**Comment by jpmschuler** [comment]
Thx for this. In my case the search worked fine, but the login got flaky. After 3.8.0 release I had around 90% successful logins (with correct, saved password) - which I didn't investigate further. 
After the last few Windows ADC patches in recent weeks I got <30% successful logins (with correct, saved password).

Adding the PR set this to 100% success again.
