### ISSUE TITLE
How to use loginExpirationTime attribute

### ISSUE THREAD

**Issue by tobiasschaeferptb** [xperseguers/t3ext-ig_ldap_sso_auth#210]
Hello,

I would like to use the loginExpirationTime attribute from a LDAP user to map it to the stop field of the TYPO3 frontend user.
The loginExpirationTime uses a format like 20240920235959Z. The stop field uses an unix timestamp.
So, there is a conversion necessary. ChatGPT recommends to create a user function like:
```
namespace Vendor\Extension\Utility;
class TimestampUtility
{
    public function convertToTimestamp($content, $conf)
    {
        $datetime = \DateTime::createFromFormat('YmdHis\Z', $content, new \DateTimeZone('UTC'));
        return $datetime ? $datetime->getTimestamp() : 'Invalid Date';
    }
}
```
But ChatGPT wasn't able to give me a working example of how to use the user function in the mapping field of the LDAP configuration for the frontend users.
Could you please give me an advise about how to get this working? Thanks!

Best regards,
Tobias Schaefer

**Comment by xperseguers** [comment]
Please see https://docs.typo3.org/p/causal/ig_ldap_sso_auth/3.8/en-us/Development/Hooks/AttributesProcessing.html

I wish you ChatGPT can help you with hooks but otherwise you read the TYPO3 documentation, it's very well explained.

**Comment by xperseguers** [comment]
Just to help a bit, https://docs.typo3.org/p/causal/ig_ldap_sso_auth/4.0/en-us/AdministratorManual/Users.html#examples shows that you can use `stdWrap` on properties, thus you need to start the [Frontend user] mapping like that:

```
...
endtime = loginExpirationTime
...
```

Then, as you said, the format is not good, thus you need to apply some `stdWrap` on it, and logically-speaking, call a user function of yours. Just read the official TYPO3 documentation about `stdWrap`: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Stdwrap.html

Reading through what's possible, it looks like `postUserFunc` (https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Stdwrap.html#postuserfunc) is a good choice. You thus change to (based on what you found with ChatGPT in the first place):

```
endtime = loginExpirationTime
endtime.postUserFunc = Vendor\Extension\Utility\TimestampUtility->convertToTimestamp
```

Then possibly adapt as I didn't test and the ChatGPT code is possibly slightly incorrect but that's basically the way to go.

Considering solved as you've enough pointers to figure the rest on your own :)
