### ISSUE TITLE
Error "ConfigurationConverter::$targetType must not be defined" in the branch feature/TYPO3v12

### ISSUE THREAD

**Issue by outdoorsman** [xperseguers/t3ext-ig_ldap_sso_auth#211]
We had to upgrade to TYPO3 v12 since v11 is no longer supported by the end of the month. So we are necessarily using the `feature/TYPO3v12` feature branch. However, I just updated to the latest 659bd3046eb7a8493798e606d448ecbd76ee59a8 and got the following error. I saw that there's some TODO notes in there, so I assume you're on this???

```
PHP Fatal error:  Type of Causal\IgLdapSsoAuth\Property\TypeConverter\ConfigurationConverter::$targetType must not be defined (as in class TYPO3\CMS\Extbase\Property\TypeConverter\AbstractTypeConverter) in /var/www/site/vendor/causal/ig_ldap_sso_auth/Classes/Property/TypeConverter/ConfigurationConverter.php on line 28
```

**Comment by siwa-pparzer** [comment]
+1

**Comment by cstrizzolo** [comment]
+1

**Comment by xperseguers** [comment]
Indeed ^^
