### ISSUE TITLE
feature/TYPO3v12 branch: Getting `PHP Fatal error: Attribute "SensitiveParameter" cannot target property`

### ISSUE THREAD

**Issue by outdoorsman** [xperseguers/t3ext-ig_ldap_sso_auth#213]
Thank you for all the new updates to the extension today 👍  I'm updated to commit cf25377fea9b1b1eb666ed58a127b8cc329e18c6 I'm now getting the error...

```
PHP Fatal error:  Attribute "SensitiveParameter" cannot target property (allowed targets: parameter) in /var/www/wwu-typo3-env1/vendor/causal/ig_ldap_sso_auth/Classes/Domain/Model/Configuration.php on line 62
```

**Comment by xperseguers** [comment]
Oups! That's the risk when you add lots of code partly blindly ^^
Thanks for that quick feedback.

**Comment by xperseguers** [comment]
More important work will happen on Thursday... stay tuned :)
