### ISSUE TITLE
Uncaught TYPO3 Exception: LDAP connection has already been closed | with PHP 8.2.20

### ISSUE THREAD

**Issue by medarob** [xperseguers/t3ext-ig_ldap_sso_auth#215]
We got an exception after updating from PHP 7.4 to 8.2.20.

An external tool in our intranet requests the news rss feed url (which works) but it's logged as an error in the Backend since the PHP update.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: LDAP connection has already been closed | Error thrown in file /var/www/intranet/public/typo3conf/ext/ig_ldap_sso_auth/Classes/Utility/LdapUtility.php in line 213. Requested URL: https://intranet.domain.de/index.php?id=100&type=9818`

**Comment by xperseguers** [comment]
Please check master branch from a few minutes ago and confirm the problem still exists.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Same error here. I did't test master, but patched the disconnect() function with the code from master. Since then the error is gone and I can definitely confirm that the try/catch (and nothing else) solved it. Thank you!

TYPO3 11.5.40
ig_ldap_sso_auth 3.8
PHP 8.2
