### ISSUE TITLE
Error on creating config record (4.0.1-dev)

### ISSUE THREAD

**Issue by tgaertner** [xperseguers/t3ext-ig_ldap_sso_auth#221]
Whenever I try to store a new configuration record I get this Error:

```
PHP Warning: Undefined array key "NEW671233b1cb753258670655" in /var/www/html/vendor/causal/ig_ldap_sso_auth/Classes/Hooks/DataHandler.php line 58
```

TYPO3 12.4.20
PHP 8.3.10

**Comment by xperseguers** [comment]
Just tried to reproduce but it works fine. Please describe the exact step you took.

I did that:

- Use Web > List on root
- Create a new LDAP configuration record
- Type "test" as name and save

=> no problem.

**Comment by tgaertner** [comment]
Exactly the same steps here. 
Tried again with a clean installation and it works without problems, so it seams to be a problem with that specific project installation. Will report back if I find the problem.

**Comment by tgaertner** [comment]
The issue was that we still had (from an update) an old field "domains" in the table "tx_igldapssoauth_config". Removing the db column solved the issue.

**Comment by xperseguers** [comment]
@tgaertner Good that you found a solution. I just tested with a TYPO3 v12 where I indeed still have that unused column in the database and it doesn't do any harm for me, just as expected in fact.

Don't know exactly how you upgraded but the only way I can think of that could lead to a problem is if you forgot to clear the system cache after upgrading, something that is always done automatically on my side when I upgrade composer dependencies.

**Comment by tgaertner** [comment]
@xperseguers Caches are definitely cleared. Its even more strange. Just renaming that field (prefix with zzz_) does not solve the problem, only really dropping the column. That's completely crazy because there should be no way this column is ever accessed or taken into account anywhere... 
Anyway, that issue is not present in a "normal" installation. Since we have a quite complex automated upgrade process (we are coming from a V6 !!!) it's probably some messed up data or whatever. Since it seams to be no issue with the extension and I can work around that issue, I close this ticket. 
Thank you for paying attention and trying to reproduce this.
