### ISSUE TITLE
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Form\SelectViewHelper: onchange.

### ISSUE THREAD

**Issue by tylkomat** [xperseguers/t3ext-ig_ldap_sso_auth#226]
In latest Typo3 11.5.41 this Error is shown when entering the LDAP/SSO backend module.
`Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Form\SelectViewHelper: onchange. Valid arguments are: additionalAttributes, data, aria, name, value, property, class, dir, id, lang, style, title, accesskey, tabindex, onclick, size, disabled, options, optionsAfterContent, optionValueField, optionLabelField, sortByOptionLabel, selectAllByDefault, errorClass, prependOptionLabel, prependOptionValue, multiple, required`

**Comment by tylkomat** [comment]
I still receive the same error. Looks like the SelectViewhelper is still evaluated although the section is not used.

**Comment by xperseguers** [comment]
Ah, interesting, thanks for the follow-up, I must admit my latest test was with TYPO3 v13.

**Comment by xperseguers** [comment]
Just debugged in TYPO3 v12, `onchange` is indeed an undeclared argument, but it is "catched" in

- `vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php:78` then passed to
- `vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractTagBasedViewHelper.php:171` as argument to be added just like that.

However, I just think that we could certainly do that instead (only for TYPO3 v12 and up):

```
diff --git a/Resources/Private/Partials/ConfigurationRecords.html b/Resources/Private/Partials/ConfigurationRecords.html
index 1a68a34..7069dab 100644
--- a/Resources/Private/Partials/ConfigurationRecords.html
+++ b/Resources/Private/Partials/ConfigurationRecords.html
@@ -52,9 +52,10 @@
             value="{currentConfiguration}"
             optionValueField="uid"
             optionLabelField="name"
-            onchange="this.form.submit();"
             class="form-select form-select-sm form-control"
-            style="display: inline-flex; width: 100%;"/>
+            style="display: inline-flex; width: 100%;"
+            additionalAttributes="{onchange: 'this.form.submit();'}"
+    />
 </f:section>
 
 </html>
```

**Comment by tylkomat** [comment]
Yes, that works under Typo3 v11 as well and removes the need to have a switch between v11 and v12+.
