### ISSUE TITLE
Call to undefined method Causal\\IgLdapSsoAuth\\Command\\ImportUsers::getLogger()

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#236]
When synchronizing via scheduler I get the following error:

Mon, 18 Nov 2024 15:26:53 +0100 [CRITICAL] request="48e6cca3f62cc" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): Error, code #0, file /var/www/vendor/causal/ig_ldap_sso_auth/Classes/Command/ImportUsers.php, line 237: Call to undefined method Causal\IgLdapSsoAuth\Command\ImportUsers::getLogger() - {"mode":"WEB","application_mode":"BE","exception_class":"Error","exception_code":0,"file":"/var/www/vendor/causal/ig_ldap_sso_auth/Classes/Command/ImportUsers.php","line":237,"message":"Call to undefined method Causal\\IgLdapSsoAuth\\Command\\ImportUsers::getLogger()","request_url":"https://www.domain.tld/typo3/module/scheduler?token=--AnonymizedToken--","exception":null}

Comes from this->logger->debug… it seems that dependency injection is not working correctly?
After commenting out the line (line 230 and 237) the task runs without problems.

**Comment by xperseguers** [comment]
Looks like this should simply be rewritten as `$this->logger` instead of former `$this->getLogger()`

**Comment by xperseguers** [comment]
Please comment on the suggested PR. Thanks for reporting!

**Comment by klodeckl** [comment]
Now another error occurs:

Mon, 18 Nov 2024 16:21:28 +0100 [CRITICAL] request="e438a816fb102" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: FE): TypeError, code #0, file /var/www/vendor/causal/ig_ldap_sso_auth/Classes/Domain/Model/Configuration.php, line 676: Cannot assign null to property Causal\IgLdapSsoAuth\Domain\Model\Configuration::$ldapTimeout of type int - {"mode":"WEB","application_mode":"FE","exception_class":"TypeError","exception_code":0,"file":"/var/www/vendor/causal/ig_ldap_sso_auth/Classes/Domain/Model/Configuration.php","line":676,"message":"Cannot assign null to property Causal\\IgLdapSsoAuth\\Domain\\Model\\Configuration::$ldapTimeout of type int","request_url":"https://www.oth-aw.de/myoth/?tx_felogin_login%5Baction%5D=login&tx_felogin_login%5Bcontroller%5D=Login&cHash=86d4de0de1a88e642be41dc90bbdd439","exception":null}

**Comment by xperseguers** [comment]
I'd say, this has nothing to do with that ticket.

Possibly I suspect you didn't go to Database analyser and you are missing a field which has been added to master branch, upcoming v4.1.0...

**Comment by klodeckl** [comment]
Yes, you’re right. I added the field in the database, works now! Thank you!

**Comment by klodeckl** [comment]
I have to bring this up again. In line 237 there is also getLogger which should be logger

**Comment by klodeckl** [comment]
Sorry, fine now…
