### ISSUE TITLE
Cannot import user from Backend when using MariaDB

### ISSUE THREAD

**Issue by ThePinkOne** [xperseguers/t3ext-ig_ldap_sso_auth#30]
I can't import users when I use an external database. 
I can establish a connection to the Active Directory, I can import groups and the user is added, when he logs in. But I can not import one special user via import button.
I don't get any kind of error message. I click 'import', the line turns green, I open the Backend users Modul and that the user is not there.

My configuration:
TYPO3 v. 8.7.16
MariaDB 10.2.6 (external, not localhost)
DB User granted all rights

The strange thing is when I use a database that's installed on the same server (as localhost), import the dump from the external db, grant the same privileges, everything works fine. And how could it be a permission issue when I can import groups manually by clicking the import button?

----- edit ---- 
I think it's a problem with the MariaDB -Version. 
Everything works finde with Maria DB v. 5.5
I can not import user via import-Button in MariaDB 10.2

**Comment by xperseguers** [comment]
This seems to be related to strict mode, not to being "external".

**Comment by ThePinkOne** [comment]
Everything works perfectly fine in the current master. So I'll close this issue :-)
