### ISSUE TITLE
multiple trusted domain

### ISSUE THREAD

**Issue by schumiel** [xperseguers/t3ext-ig_ldap_sso_auth#32]
Hi,

supports the extension to use multiple directories?

Best Regards
schumiel

Edit title.

**Comment by xperseguers** [comment]
Please better describe what you want to achieve. I really don't get what you mean by "multiple directories".

**Comment by xperseguers** [comment]
and here is the doc (as any other TYPO3 extension), maybe this helps: https://docs.typo3.org/typo3cms/extensions/ig_ldap_sso_auth/

**Comment by schumiel** [comment]
Sorry, I meant multiple trusted domain.

I have users in several trusted domains. LDAP can normally only handle one trusted domain. Can your extension be more than one?

Sorry for my bad English.

**Comment by xperseguers** [comment]
You may create multiple LDAP configuration, so I guess the answer to your question is yes.

**Comment by schumiel** [comment]
Do you mean the LDAP configurations in your extension, or do you mean that I need multiple LDAP interfaces?
If you mean the former, do you have a link to the documentation that describes it? Unfortunately, I can not find this. Sorry.

**Comment by xperseguers** [comment]
The easiest would be to try out this extension, looks like you did not even try. After all that's the only one providing LDAP for TYPO3.

**Comment by schumiel** [comment]
Yes that's right. I have not tried it yet because I want to know if it does what I want. :-)
