### ISSUE TITLE
Allow importing more than 100 users

### ISSUE THREAD

**Issue by spoonerWeb** [xperseguers/t3ext-ig_ldap_sso_auth#34]
Currently the import scheduler task is set fixed to fetch 100 records if the function `ldap_control_paged_result()` exists.

One should either be possible to change the `PAGE_SIZE` or to always fetch all records.
The possibility of import users page by page is not possible to handle in the scheduler task.

**Comment by someplace53** [comment]
I have seen this to late, but this seems to be related to #43 where I proposed a fix. And if you must you could change the page size in the code (same class at the top)

**Comment by xperseguers** [comment]
#43 has been fixed (sorry @someplace53, could not commit in your name since I don't know who you are and you didn't provide a PR that I could have used). Please check and report if problem persists.

**Comment by spoonerWeb** [comment]
@xperseguers It's not working with version 3.5.0.

Behaviour:
I have 380 FE users.
I disable all of them.
I activate to re-enable imported ones.
After first import run: 100 FE users are enabled
After second and third import run: Still 100 FE users are enabled.
The other 280 FE users stay disabled.

**Comment by fvb-sb** [comment]
Same here.

Running a ldapsearch on server's CLI using the same LDAP filter returns the expected number of entries. Seems that the search wizard as well as the import task are limited to 100 FE users.

@xperseguers: Is there any chance to tweak this?

**Comment by xperseguers** [comment]
The import is supposed to take advantage of pagination and thus import all possible records with multiple "ldap fetch". Since that ticket is quite old, would you mind testing again and reporting with the current version of the app? Thanks.

**Comment by klodeckl** [comment]
Pagination never worked for me (with eDirectory). I use the following patch for this:

```
diff --git a/Classes/Utility/LdapUtility.php b/Classes/Utility/LdapUtility.php
--- a/Classes/Utility/LdapUtility.php
+++ b/Classes/Utility/LdapUtility.php
@@ -45,12 +45,12 @@
  */
 class LdapUtility
 {
-    const PAGE_SIZE = 100;
+    const PAGE_SIZE = 100000;
 
     /**
      * Only used if pagination fails to be initialized
      */
-    const MAX_ENTRIES = 500;
+    const MAX_ENTRIES = 50000;
 
     /**
      * LDAP Server charset

```
