### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by fgoe** [xperseguers/t3ext-ig_ldap_sso_auth#35]
We are doing a complete reboot of our webserver with SLES15 which has php 7.2.5 included.
The ldap extension fails and I've seen the php < 7.1.99 in the dependencies.
Is there a definitve blocker for going up to 7.2.x ?

**Comment by xperseguers** [comment]
Switch to master branch. It is already marked as compatible with PHP 7.2.

**Comment by spoonerWeb** [comment]
Is there a release planned with PHP 7.2 support?
