### ISSUE TITLE
Nested user groups wont be fetched when using the scheduler

### ISSUE THREAD

**Issue by utrotzek** [xperseguers/t3ext-ig_ldap_sso_auth#36]
The handling of the parentGroup mapping only works if I manually click "import" on one explicit group in the backend module. When I use the scheduler to synchronize all groups, the parentGroups are not handled at all. 

Is this a bug or a desired behaviour? Am I possible to synchronize all groups with parent groups at once somehow?

**Comment by xperseguers** [comment]
This sounds like a bug because the scheduler importer is supposed to behave relatively similarly than the manual import, at least for such use case.

**Comment by xperseguers** [comment]
This issue will be closed in a few weeks if there's no more feedback in relation with either latest release (v4.0.0) or master branch (upcoming v4.0.1).
