### ISSUE TITLE
Configure LDAP to access multiple hosts

### ISSUE THREAD

**Issue by cybarg** [xperseguers/t3ext-ig_ldap_sso_auth#39]
Hello,

we have a project where we need to connect to multiple LDAP Servers with different hosts on different IPs with different LDAP structures.

Where can I find documentation for this, how is this to be done?
Do you have a sample file for this?

Thank you for your support.
Kind regards,
Carsten

**Comment by xperseguers** [comment]
Looks like you just want to create multiple LDAP configuration records.
