### ISSUE TITLE
column 'tx_igldapssoauth_dn' used in key specification without a key length

### ISSUE THREAD

**Issue by tomasnorre** [xperseguers/t3ext-ig_ldap_sso_auth#4]
When updating to latest version and doing a schemaup with TYPO3 Console `./bin/typo3cms database:updateschema`, I get following error:

The following errors occurred:
| Type          | Message                                                                               |
| Add fields  | BLOB/TEXT column 'tx_igldapssoauth_dn' used in key specification without a key length |
|            |                                                                                       |
|            | BLOB/TEXT column 'tx_igldapssoauth_dn' used in key specification without a key length |
|            |                                                                                       |
|            | BLOB/TEXT column 'tx_igldapssoauth_dn' used in key specification without a key length |
|            |                                                                                       |
|            | BLOB/TEXT column 'tx_igldapssoauth_dn' used in key specification without a key length |

I'm not completely sure what the right fix is, but if you have a suggestion I would be happy to test.

TYPO3: 8.7.9
Version: dev-master

**Comment by xperseguers** [comment]
According to https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/ext_tables.sql all fields `tx_igldapssoauth_dn` are of type `VARCHAR(255)`. Somehow it looks like those columns are of type `TEXT` or `BLOB` in your database. Please check and report why.

**Comment by tomasnorre** [comment]
Hmm.. 

When I look at the `explain be_users` and `explain be_groups` both looks varchar to me. 

be_users:
<img width="709" alt="screen shot 2018-01-18 at 11 41 21" src="https://user-images.githubusercontent.com/1212481/35094156-ca361830-fc44-11e7-8b1e-74e080e02ada.png">
be_groups
<img width="696" alt="screen shot 2018-01-18 at 11 41 39" src="https://user-images.githubusercontent.com/1212481/35094157-ca5b071c-fc44-11e7-9d18-d7b678597951.png">

**Comment by xperseguers** [comment]
Then please try to update schema from Install Tool and look which queries are trying to be executed. It's not clear then what the problem is.

**Comment by tomasnorre** [comment]
That's all it says related to tx_igldapssoauth fields. 

<img width="588" alt="screen shot 2018-01-18 at 12 00 04" src="https://user-images.githubusercontent.com/1212481/35094973-4417d8d0-fc47-11e7-9019-9a283d5505b8.png">

It works from install-tool, now I have the keys added.. 

The problem must be at my local setup then.. Thanks for you fast response. I'll dig into this, and report if I find the problem. 

Feel free to close the ticket.
