### ISSUE TITLE
Mapping of username in BE_USERS

### ISSUE THREAD

**Issue by Pit-Storm** [xperseguers/t3ext-ig_ldap_sso_auth#47]
Hi Xavier,

we would like to set up this plugin, but the Mapping of "username = <samaccountname>" ist not working. If I look to the Search-Assistent the mapping preview says: username = <>

Can you give a hint?

Kind regards.
Peter

**Comment by oheil** [comment]
We have as mapping:
username = <sAMAccountName>
It is a Microsoft Active Directory.

**Comment by xperseguers** [comment]
Username cannot be mapped. It is mapped automatically based on the filter you give. See https://docs.typo3.org/typo3cms/extensions/ig_ldap_sso_auth/AdministratorManual/SampleConfiguration.html#fe-users

**Comment by Pit-Storm** [comment]
Thanks. Now I got it. You have to include the uid = {USERNAME} with an AND-Condition to your search criteria. This schould be an example in the Docs to make that clear.
