### ISSUE TITLE
TYPO3 v9 locally-assigned TYPO3 user groups are not kept

### ISSUE THREAD

**Issue by oheil** [xperseguers/t3ext-ig_ldap_sso_auth#49]
"Keep locally-assigned TYPO3 user groups" ist enabled but the group relation to local groups is lost after login.

Found the error in
Classes/Domain/Repository/Typo3UserRepository.php
line 375:
`$localUserGroups = array_keys($rows);`

I have replaced this line with
`$localUserGroups = array_map(function($row){return $row['uid'];},$rows);`
as a solution.

**Comment by xperseguers** [comment]
Tested with locally-assigned groups to a Backend user and I cannot reproduce your problem.

**Comment by xperseguers** [comment]
Looks like you were still using the older version of the code, not yet migrated to Doctrine, and thus only possibly compatible with TYPO3 v8.

**Comment by oheil** [comment]
Yes, this is possible. I am still on my local clone. So I close :-)
