### ISSUE TITLE
no error message on login for deactivated/expired accounts

### ISSUE THREAD

**Issue by DerVolli** [xperseguers/t3ext-ig_ldap_sso_auth#5]
If an account has an expiration date set in Typo3 BE and exceeds it the respective user doesn't get any error message if the user tries to log on. The login page is just reloaded and the username is prefilled.
This is also true if the account is disabled in the Typo3 BE.

This has been observed with Typo3 6.2 and 7.6

**Comment by xperseguers** [comment]
Did you confirm that TYPO3, regardless of this extension, normally shows a dedicated message under such case and that this extension somehow changes this behaviour?

**Comment by DerVolli** [comment]
Yes I did test that.

**Comment by xperseguers** [comment]
Looks like I cannot reproduce this problem with `feature/TYPO3_v9`. In fact, start/end times are actually not taken into account anymore.

**Comment by DerVolli** [comment]
Thanks a lot - that helped!
