### ISSUE TITLE
Change limit for amount of users to a configurable value (function getAvailableUsers)

### ISSUE THREAD

**Issue by tobiasschaeferptb** [xperseguers/t3ext-ig_ldap_sso_auth#50]
Hi Xavier,

could you please change the limit for the amount of users in function getAvailableUsers (Classes/Controller/ModuleController.php line 674) to a configurable value instead of the hardcoded 2000. I suggest to make it configurable throught the extension manager (e.g. in the basic tab) or in the ldap configuration (e.g. in the ldap tab).

Cheers, Tobias

**Comment by xperseguers** [comment]
As the comment states:

```
 // Current Extbase implementation does not properly handle
// very large data sets due to memory consumption and waiting
// time until the list starts to be "displayed". Instead of
// waiting forever or drive code to a memory exhaustion, better
// stop sooner than later
```

to me instead of showing more than 2000 records (which is already huge), the module should possibly be enhanced to allow filtering and thus be allowed to "search" for users to be imported.

**Comment by githubUser123444** [comment]
Hi Xavier, 

as this issue is not closed yet, i am asking you to rethink your decision not to make the default limit of importable ldap users (2000) editable from the backend. 

Line 709 in Classes/Controller/ModuleController.php

` if (count($users) >= 2000) {
                break;
}`

Cheers, Felix

**Comment by fishbone1** [comment]
Also, is there an option to import the user on login, if it doesn't exist? We have about 5000 users. Many will never login. I thought this is what TYPO3FEUserExist option is for, but unchecking it doesn't work.

**Comment by xperseguers** [comment]
@fishbone1 That's the default behaviour, if it "doesn't" work, you're probably missing something related to user groups. Please check that the user gets created in table `fe_users`, if it does but is marked as "deleted" then you mixed-up group configuration, like enforcing user groups but without mapping them.

**Comment by fishbone1** [comment]
@xperseguers Yes, it works. Great! The missing users had wrong OUs.
