### ISSUE TITLE
Fail reading extension configuration in TYPO3 9

### ISSUE THREAD

**Issue by christian-fries** [xperseguers/t3ext-ig_ldap_sso_auth#51]
I just tried to install the master branch in a TYPO3 9 project. After the installation using `composer require causal/ig_ldap_sso_auth:dev-master` i get an error message:

`Warning: unserialize() expects parameter 1 to be string, array given in /Users/christian/Projects/Typo39Project/web/typo3conf/ext/ig_ldap_sso_auth/ext_localconf.php line 8`

As it seems, the extension configuration in TYPO3 9 isn't stored as a serialized string anymore but as an array. That's why the `unserialize()` command fails.

**Comment by xperseguers** [comment]
Oh my! This is due to commit d57c86a54da21109505eea851087025847eb9467 which was reported by someone and I incorrectly tested it. on it.
