### ISSUE TITLE
ClassAliasMap removed, but still mentioned in composer.json

### ISSUE THREAD

**Issue by jpmschuler** [xperseguers/t3ext-ig_ldap_sso_auth#58]
Upon installing  `3.4.0` composer shows a warning: ```The class alias map file "Migrations/Code/ClassAliasMap.php" configured in package "causal/ig_ldap_sso_auth" was not found!``` as the php file was removed in 02980a0 but `composer.json` wasn't updated

**Comment by MarkusEhrlich** [comment]
This fix did not land in version 3.4.0. There, this warning still appears when you run Composer.
