### ISSUE TITLE
Allow setting LDAPTLS_REQCERT=never

### ISSUE THREAD

**Issue by sbusemann** [xperseguers/t3ext-ig_ldap_sso_auth#61]
As an admin, I like to setup the LDAP/PHP parameter 'LDAPTLS_REQCERT=never

**AC:**
* Configuration for this setting is disabled by default
* If enabled, the putenv('LDAPTLS_REQCERT=never'); is activated

**Comment by xperseguers** [comment]
This is possible already, at least on master branch, please use the checkbox "TLS require cert" (which should in your case not be ticked).
