### ISSUE TITLE
Add support for site configuration domains

### ISSUE THREAD

**Issue by jonakieling** [xperseguers/t3ext-ig_ldap_sso_auth#67]
Hi everyone,

since TYPO3 9 we can set up our domains with the site configurations. I have prepared a PR #60  that adds domains from site configurations alongside the domains from domain records for the authentication restriction. The domains are added to the central list of domains.

Any tests and feedback are appreciated.

All the best
jona

**Comment by xperseguers** [comment]
Hello. You have closed your PR, don't know if this is still valid? If so, and after having a quick look at the PR, feel free to open it again while fixing obvious typos such as additional blank spaces in `use`, sticking to conventions used for commit message etc.

**Comment by xperseguers** [comment]
This change will actually be needed for full non-legacy compatibility already with TYPO3 v9. In TYPO3 v10, table `sys_domain` does not exist anymore.

This is not urgent, but we will need to mark the usage of `sys_domain` in TYPO3 v9 as deprecated once this support for site configuration has landed to master.
