### ISSUE TITLE
syntax error, unexpected '?' with PHP 7.3

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#68]
I just updated to Debian 10 -> new PHP 7.3. I got the following error message:

syntax error, unexpected '?' 
ParseError thrown in file
/var/www/nfs/htdocs/typo3conf/ext/ig_ldap_sso_auth/Classes/Domain/Repository/ConfigurationRepository.php in line 102.

So I changed
    public function findByUid(int $uid): ?Configuration
to
    public function findByUid($uid)

(like in a previous ext version).

TYPO3 8.7.24.

**Comment by xperseguers** [comment]
Looks like you are not using PHP 7.3 like you seem to say. Please check.

**Comment by klodeckl** [comment]
I know what you mean, but I do, PHP Version 7.3.4-2. I am currently trying to reproduce it another time, but can’t find the error. What could I execute to get into the function?

**Comment by klodeckl** [comment]
Oh you are right. It was a subdomain with a different nginx configuration which was still on PHP 7.0. Sorry.
