### ISSUE TITLE
Scheduler sync task always updates timestamp

### ISSUE THREAD

**Issue by itzonban** [xperseguers/t3ext-ig_ldap_sso_auth#71]
Hi,

we are using the sync task to delete FE users which are no longer in LDAP.  To finally erase them from the database we use the TYPO3 recycler task. But here is the problem: the recycler task requires an "older than X days" entry. Everytime the sync task is running the fe_user.tstamp field is updated for every user, so the entry can never be older than 1 day. 

As a workaround it is possible to run the sync every 2 days, but IMHO it would be more accurate when the timestamp is only updated when there is in fact an update action for the user...

Best regards
Daniel

**Comment by xperseguers** [comment]
Please try to comment out Lines 263 to 265 here: https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Domain/Repository/Typo3UserRepository.php#L263-L265 and in the same file lines 302-304 and report.

**Comment by itzonban** [comment]
Sorry for my late response, I was out of office. 

Thanks for the fix in 3.5.0!

I retested and the timestamp of users, who are already set to "deleted=1", doesn't update anymore. Only for users changing from 0 to 1 or staying at 0.
