### ISSUE TITLE
LDAP_DEREF_NEVER Exception

### ISSUE THREAD

**Issue by Dysadia** [xperseguers/t3ext-ig_ldap_sso_auth#77]
Hey,

I got this error the first time, when I wanted to access LDAP/SSO in System. Since I haven't had configured the extension in the first place I kept going without giving it too much of attention.
After having everything set up and starting the scheduler the same error occured again.

I am currently running Typo3 9.5.5 - PHP-Version: 7.3.6
I also tried to reinstall the extension after deinstalling and cleaning the data. Unfortunately the error still occurs as soon as the extension has to do something.

I am very sorry, since I am no pro with typo3 extbase programming and since I am the only one having the issue, it might be an error on my side.

This is the whole exception code:
PHP Warning: Use of undefined constant LDAP_DEREF_NEVER - assumed 'LDAP_DEREF_NEVER' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\typo3\sysext\extbase\Classes\Reflection\ClassSchema.php line 522

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Use of undefined constant LDAP_DEREF_NEVER - assumed 'LDAP_DEREF_NEVER' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\typo3\sysext\extbase\Classes\Reflection\ClassSchema.php line 522 | TYPO3\CMS\Core\Error\Exception thrown in file C:\xampp\htdocs\typo3\sysext\core\Classes\Error\ErrorHandler.php in line 116. Requested URL: http://infoterminal/typo3/index.php?route=%%2Fsystem%%2FIgLdapSsoAuthTxigldapssoauthm1%%2F&token=--AnonymizedToken--

Probably an issue with my php? I would appreciate your help. Sorry for the extra work :/

**Comment by xperseguers** [comment]
Hello. Since you closed this issue I suppose you found the cause but it would be possibly useful if you could explain, if someone finds somehow this post and looks for a solution...

**Comment by Dysadia** [comment]
Hey,

this was just my own stupidity... I had  to enable ldap in my xampp/php configuration!

**Comment by xperseguers** [comment]
Great then! :) The extension is supposed to warn you that the LDAP extension is not loaded but possibly you used another entry point than the Backend module and did not get the warning.

**Comment by Dysadia** [comment]
I did use the Backend Module as first entry point :/ But since I am the only one with this issue it might not be that problematic.
Thank you very much for your time :)
