### ISSUE TITLE
Get Typo3 Exception at the current version 3.4.0

### ISSUE THREAD

**Issue by topsnet-holgerd** [xperseguers/t3ext-ig_ldap_sso_auth#78]
Running Typo3 8.7.28 and ig_ldap_sso_auth version 3.4.0 (latest) with PHP 7.2.23, getting permanent Typo3 Exception in t3 log:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: syntax error, unexpected '?' | ParseError thrown in file /var/www/clients/client21/web84/web/typo3conf/ext/ig_ldap_sso_auth/Classes/Domain/Repository/ConfigurationRepository.php in line 102

**Comment by xperseguers** [comment]
You are thus referring to https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/b7c3366553e526fd57489ac66d07a081add5aadc/Classes/Domain/Repository/ConfigurationRepository.php#L102

This is a feature available since PHP 7.1, please see https://www.php.net/manual/en/migration71.new-features.php. If you get this error then you are not really running PHP 7.2.23 as you write.

**Comment by topsnet-holgerd** [comment]
Dear xperseguers,
I consulted the phpinfo for the PHP-Version. Typo3 works but in the syslog I get from 10 to 20 of those messages every day. It doesn't say PHP-Error, it says uncaught Typo3 Exception due to parsing error.
I will check again and ask our system engineer, what about PHP-Version.

**Comment by xperseguers** [comment]
If TYPO3 "works", then possibly this is not related to the version used by TYPO3 but the version used with your scheduler script, which is PHP-cli and could easily be an older version of PHP, not the one used by PHP-fpm or mod_php (Apache). You should double-check this as well.

**Comment by topsnet-holgerd** [comment]
Dear Xavier,
thanks a lot, it has been the scheduler.
Best, Holger
 
Von: Xavier Perseguers <notifications@github.com> 
Gesendet: Mittwoch, 30. Oktober 2019 10:53
An: xperseguers/t3ext-ig_ldap_sso_auth <t3ext-ig_ldap_sso_auth@noreply.github.com>
Cc: topsnet-holgerd <hd@tops.net>; Author <author@noreply.github.com>
Betreff: Re: [xperseguers/t3ext-ig_ldap_sso_auth] Get Typo3 Exception at the current version 3.4.0 (#78)
 
If TYPO3 "works", then possibly this is not related to the version used by TYPO3 but the version used with your scheduler script, which is PHP-cli and could easily be an older version of PHP, not the one used by PHP-fpm or mod_php (Apache). You should double-check this as well.
