### ISSUE TITLE
E-Mail as Username

### ISSUE THREAD

**Issue by FlorianX** [xperseguers/t3ext-ig_ldap_sso_auth#81]
In  our scenario the username is the mail of a user. We only have one LDAP configuration. If we want to use SSO for the users this does not work, while the username is always exploded on the \@ 

https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/135f1a3f4dbf259c95eae3db5ae182d99c7a5b26/Classes/Service/AuthenticationService.php#L129-L138

Could it be a feature to toggle this behaviour on/off?

**Comment by FlorianX** [comment]
May be related to #66?

**Comment by xperseguers** [comment]
indeed!

**Comment by xperseguers** [comment]
@FlorianX if you're still willing to have that, please check and comment on the PR #87

**Comment by FlorianX** [comment]
PR #87 looks good
