### ISSUE TITLE
Problems with mysql in strict mode and TYPO3 v10

### ISSUE THREAD

**Issue by koernchen02** [xperseguers/t3ext-ig_ldap_sso_auth#84]
When running mysql in strict mode, ldap configs are not persistable, because the `domains` column can't have a default value since it is of type TEXT. Asking for advice on slack , concerning changing the sql migration based on the used TYPO3 version, I was pointed to:

https://github.com/koninklijke-collective/koning_phinx/blob/3d43492be0d0a25006062d3dd24b3c2dfa8047bd/ext_localconf.php#L13

https://github.com/koninklijke-collective/koning_phinx/blob/3d43492be0d0a25006062d3dd24b3c2dfa8047bd/Classes/Migration/DatabaseSchemaService.php#L34

Now I'm asking myself, would you accept a pull request in this "direction"?
I mean getting rid of ext_tables.sql and migrate the table based on this signal/hook practice or would you rather introduce a TYPO3 10 specific Version that get's rid of the version compares and simply drop that column from the migration definition in ext_tables.sql

I would be happy to provide a pull request, but wanted to make sure what your thought on this topic are! (Since it is indeed requiring quite some effort for getting rid of one column :)

**Comment by xperseguers** [comment]
I'd be interested into having a PR in that direction, getting rid of `ext_tables.sql` and having something "modern", thus handling differences in various TYPO3 versions just sounds good!

**Comment by xperseguers** [comment]
Closed as no further feedback and possibly fixed in the mean time (see #80).
