### ISSUE TITLE
Fehlermeldung undefined bei Update von Gruppen

### ISSUE THREAD

**Issue by cooltypo** [xperseguers/t3ext-ig_ldap_sso_auth#85]
Typo3-Version: 8.7
LDAP-VErsion:3.5.0

Import, Löschen und Undelete von Gruppen möglich
Import von Usern möglich
Update von Gruppen **NICHT MÖGLICH**
Beim Import Modul für Gruppen:
Bei Klick auf den Button upgrade einer beliebigen Gruppe kommt ein kleines Fenster mit der Fehlermeldung:
"undefined"

**Comment by xarius74** [comment]
Soweit wir festgestellt haben, kommt diese Fehlermeldung, wenn es zu KEINER Änderung in der Datenbank kommt. D.h. wenn die Informationen in der DB sowieso schon aktuell sind.

**Comment by xperseguers** [comment]
Good to know. Please stick to English, this is an English-first project and tickets should be understandable by anyone.
