### ISSUE TITLE
ServerType(Active Directory) does not work - No BE Users will be found

### ISSUE THREAD

**Issue by xarius74** [xperseguers/t3ext-ig_ldap_sso_auth#86]
No BE users will be found. LDAP reports an "operations error". 

Looks like servertype is not translated in Module LdapUtility.php and default is 'OpenLDAP'

        if ($serverType === 'Active Directory') {
            @ldap_set_option($this->connection, LDAP_OPT_REFERRALS, 0);
        }

**Comment by xperseguers** [comment]
Already fixed in master branch and for a short time released as well: https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/commit/43be6f02eb9680105ea73778c0a632214c8f886d
