### ISSUE TITLE
Recover hidden users if the import task did not end properly

### ISSUE THREAD

**Issue by ismab** [xperseguers/t3ext-ig_ldap_sso_auth#92]
Hello, 
Thanks for your extension. 
When the import task could not end due to a server interruption (for exemple if Apache restart during the execution of the import task) the users stay hidden. Do you know if there is a way to recover hidden users in this case ?

**Comment by xperseguers** [comment]
That's a bit strange since the import is supposed to change database using a transaction, which should logically only be persisted at the end and thus should leave the DB intact if it gets interrupted.

**Comment by xperseguers** [comment]
Possibly could be "enhanced" with #135

=> closing this issue as really old, transaction is supposed to do its job and server interruption sounds like a big problem anyway
