### ISSUE TITLE
Problem with Convert from Active Directoy into SQL Server Express with Typo3 9.5.14

### ISSUE THREAD

**Issue by typo3noob** [xperseguers/t3ext-ig_ldap_sso_auth#93]
Hello @ all,

At the moment i´m trying to get ldap 3.5.1 into typo3 9.5.14 but only get the following error at the import from the AD:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'INSERT INTO...

...SQLSTATE [42000, 257]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Die implizite Konvertierung vom char-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen. SQLSTATE [42000, 8180]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Anweisung(en) konnte(n) nicht vorbereitet werden. | Doctrine\DBAL\DBALException thrown in file C:\inetpub\wwwroot\typo3\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php in line 169. Requested URL: http://localhost/typo3/index.php?route=%%2Fajax%%2Fldap%%2Fusers%%2Fimport&token=--AnonymizedToken--&configuration=5&mode=fe&.....

**Translated into english:** The implicit conversion from char datatype to varbinary(max) is not allowed. Use the CONVERT function to execute this query.

statement(s) could not be prepared.

Information: Windows Server 2019, IIS 10, PHP 7.4, SQL Express 2019, Typo3 9.5.14, ldap 3.5.1

Is there a way how i can fix this?

Best regards

**Comment by xperseguers** [comment]
Sounds like a problem with Doctrine, you should analyse the complete `INSERT INTO` statement and find exactly which field is posing problem, then we can see where the problem is exactly but sounds like some kind of problem in Doctrine, not directly with this extension.
